In [115]:
import pandas as pd
import numpy as np

# Bloomington Data Cleaning

## Use of Force

Read in the datasets.

### 2019

In [116]:
uofB1_19 = pd.read_excel (r'Use of Force/Bloomington/2019/2019-first-quarter-use-of-force.xlsx')
uofB2_19 = pd.read_excel (r'Use of Force/Bloomington/2019/2019-second-quarter-use-of-force.xlsx')
uofB3_19 = pd.read_excel (r'Use of Force/Bloomington/2019/2019-third-quarter-use-of-force.xlsx')
uofB4_19 = pd.read_excel (r'Use of Force/Bloomington/2019/2019-fourth-quarter-use-of-force.xlsx')

uof_19 = pd.concat([uofB1_19, uofB2_19, uofB3_19, uofB4_19])
uof_19 = uof_19.drop(columns = ['Draw Less Lethal'])

### 2018

In [117]:
uofB1_18 = pd.read_excel (r'Use of Force/Bloomington/2018/2018-first-quarter-use-of-force.xlsx')
uofB2_18 = pd.read_excel (r'Use of Force/Bloomington/2018/2018-second-quarter-use-of-force.xlsx')
uofB3_18 = pd.read_excel (r'Use of Force/Bloomington/2018/2018-third-quarter-use-of-force.xlsx')
uofB4_18 = pd.read_excel (r'Use of Force/Bloomington/2018/2018-fourth-quarter-use-of-force.xlsx')

uof_18 = pd.concat([uofB1_18, uofB2_18, uofB3_18, uofB4_18])

### 2017

In [118]:
uofB1_17 = pd.read_excel (r'Use of Force/Bloomington/2017/2017-first-quarter-use-of-force.xlsx')
uofB2_17 = pd.read_excel (r'Use of Force/Bloomington/2017/2017-second-quarter-use-of-force.xlsx')
uofB3_17 = pd.read_excel (r'Use of Force/Bloomington/2017/2017-third-quarter-use-of-force.xlsx')
uofB4_17 = pd.read_excel (r'Use of Force/Bloomington/2017/2017-fourth-quarter-use-of-force.xlsx')

uof_17 = pd.concat([uofB1_17, uofB2_17, uofB3_17, uofB4_17])

### 2016

In [119]:
uofB1_16 = pd.read_excel (r'Use of Force/Bloomington/2016/2016-first-quarter-use-of-force.xlsx')
uofB2_16 = pd.read_excel (r'Use of Force/Bloomington/2016/2016-second-quarter-use-of-force.xlsx')
uofB3_16 = pd.read_excel (r'Use of Force/Bloomington/2016/2016-third-quarter-use-of-force.xlsx')
uofB4_16 = pd.read_excel (r'Use of Force/Bloomington/2016/2016-fourth-quarter-use-of-force.xlsx')

uof_16 = pd.concat([uofB1_16, uofB2_16, uofB3_16, uofB4_16])
uof_16 = uof_16.reset_index()
uof_16 = uof_16.drop([0, 293])
uof_16['Date'] = pd.to_datetime(uof_16['Date']).dt.date

### Combine all years into one DataFrame

In [120]:
uof_all_years = pd.concat([uof_19, uof_18, uof_17, uof_16]).reset_index().drop(columns = ['index'])

### Fill null values with 0 for quantitative categories and Uknown for qualitative categories
* The null values here represent that that suspect was not of that race, meaning that there is a 1 in another category of his/her respective race. So to be able to tell that they are not of that race, instead we fill it with the value of 0.

In [121]:
uof_all_years = uof_all_years.fillna(value = {'Suspect Gender Female' : 0, 'Suspect Gender Male': 0, 
                                              'Suspect Race  Caucasian, Hispanic': 0, 
                                              'Suspect Race Caucasian, Non-Hispanic': 0, 
                                              'Suspect Race African American, Non-Hispanic': 0, 
                                              'Suspect Race African American, Hispanic': 0, 
                                              'Suspect Race Indian/Alaskan Native, Non-Hispanic': 0, 
                                              'Suspect Race Indian/Alaskan Native, Hispanic': 0,
                                              'Suspect Race Asian/Pacific Islander, Non-Hispanic': 0, 
                                              'Suspect Race Asian/Pacific Islander, Hispanic': 0, 
                                              'District': 'Unknown', 'Suspect Condition': 'Unknown', 
                                              'Suspect Role': 'Unknown' })

uof_all_years['Year'] = pd.DatetimeIndex(uof_all_years['Date']).year
uof_all_years = uof_all_years.drop(['level_0'], axis = 1)

### Exporting this DataFrame to a .csv for external purposes, optional step

In [122]:
uof_all_years.to_csv('bloom_uof.csv')

### Take the sum of all the 1's in each race's column, to get the total number of persons in that race

In [123]:
white_uof_19 = uof_all_years[uof_all_years['Year'] == 2019]['Suspect Race Caucasian, Non-Hispanic'].sum()
black_uof_19 = uof_all_years[uof_all_years['Year'] == 2019]['Suspect Race African American, Non-Hispanic'].sum()
latinx_uof_19 = uof_all_years[uof_all_years['Year'] == 2019]['Suspect Race  Caucasian, Hispanic'].sum()
asian_uof_19 = uof_all_years[uof_all_years['Year'] == 2019]['Suspect Race Asian/Pacific Islander, Non-Hispanic'].sum()
other_uof_19 = uof_all_years[uof_all_years['Year'] == 2019]['Suspect Race Indian/Alaskan Native, Hispanic'].sum() 
+ uof_all_years[uof_all_years['Year'] == 2019]['Suspect Race Indian/Alaskan Native, Non-Hispanic'].sum() 
+ uof_all_years[uof_all_years['Year'] == 2019]['Suspect Race Asian/Pacific Islander, Hispanic'].sum() 
+ uof_all_years[uof_all_years['Year'] == 2019]['Suspect Race African American, Hispanic'].sum()

white_uof_18 = uof_all_years[uof_all_years['Year'] == 2018]['Suspect Race Caucasian, Non-Hispanic'].sum()
black_uof_18 = uof_all_years[uof_all_years['Year'] == 2018]['Suspect Race African American, Non-Hispanic'].sum()
latinx_uof_18 = uof_all_years[uof_all_years['Year'] == 2018]['Suspect Race  Caucasian, Hispanic'].sum()
asian_uof_18 = uof_all_years[uof_all_years['Year'] == 2018]['Suspect Race Asian/Pacific Islander, Non-Hispanic'].sum()
other_uof_18 = uof_all_years[uof_all_years['Year'] == 2018]['Suspect Race Indian/Alaskan Native, Hispanic'].sum() 
+ uof_all_years[uof_all_years['Year'] == 2018]['Suspect Race Indian/Alaskan Native, Non-Hispanic'].sum() 
+ uof_all_years[uof_all_years['Year'] == 2018]['Suspect Race Asian/Pacific Islander, Hispanic'].sum() 
+ uof_all_years[uof_all_years['Year'] == 2018]['Suspect Race African American, Hispanic'].sum()

white_uof_17 = uof_all_years[uof_all_years['Year'] == 2017]['Suspect Race Caucasian, Non-Hispanic'].sum()
black_uof_17 = uof_all_years[uof_all_years['Year'] == 2017]['Suspect Race African American, Non-Hispanic'].sum()
latinx_uof_17 = uof_all_years[uof_all_years['Year'] == 2017]['Suspect Race  Caucasian, Hispanic'].sum()
asian_uof_17 = uof_all_years[uof_all_years['Year'] == 2017]['Suspect Race Asian/Pacific Islander, Non-Hispanic'].sum()
other_uof_17 = uof_all_years[uof_all_years['Year'] == 2017]['Suspect Race Indian/Alaskan Native, Hispanic'].sum() 
+ uof_all_years[uof_all_years['Year'] == 2017]['Suspect Race Indian/Alaskan Native, Non-Hispanic'].sum() 
+ uof_all_years[uof_all_years['Year'] == 2017]['Suspect Race Asian/Pacific Islander, Hispanic'].sum() 
+ uof_all_years[uof_all_years['Year'] == 2017]['Suspect Race African American, Hispanic'].sum()


white_uof_16 = uof_all_years[uof_all_years['Year'] == 2016]['Suspect Race Caucasian, Non-Hispanic'].sum()
black_uof_16 = uof_all_years[uof_all_years['Year'] == 2016]['Suspect Race African American, Non-Hispanic'].sum()
latinx_uof_16 = uof_all_years[uof_all_years['Year'] == 2016]['Suspect Race  Caucasian, Hispanic'].sum()
asian_uof_16 = uof_all_years[uof_all_years['Year'] == 2016]['Suspect Race Asian/Pacific Islander, Non-Hispanic'].sum()
other_uof_16 = uof_all_years[uof_all_years['Year'] == 2016]['Suspect Race Indian/Alaskan Native, Hispanic'].sum() 
+ uof_all_years[uof_all_years['Year'] == 2016]['Suspect Race Indian/Alaskan Native, Non-Hispanic'].sum() 
+ uof_all_years[uof_all_years['Year'] == 2016]['Suspect Race Asian/Pacific Islander, Hispanic'].sum() 
+ uof_all_years[uof_all_years['Year'] == 2016]['Suspect Race African American, Hispanic'].sum()

0.0

## Stop Data / Citations

Read in the datasets.

### 2016 - 2019

In [124]:
cit_19 = pd.read_excel (r'Citations/Bloomington/2019.xlsx')
cit_18 = pd.read_excel (r'Citations/Bloomington/2018.xlsx')
cit_17 = pd.read_excel (r'Citations/Bloomington/2017.xlsx')
cit_16 = pd.read_excel (r'Citations/Bloomington/2016.xlsx')

### Fill null values with Unknown

In [125]:
cit_19 = cit_19.fillna('Unknown')
cit_18 = cit_18.fillna('Unknown')
cit_17 = cit_17.fillna('Unknown')
cit_16 = cit_16.fillna('Unknown')

### Merge all years together

In [126]:
cit_19['Year'] = 2019
cit_18['Year'] = 2018
cit_17['Year'] = 2017
cit_16['Year'] = 2016
cit_bloom_merged = pd.concat([cit_19, cit_18, cit_17])
cit_bloom_merged
cit_bloom_merged.to_csv('all_cities.csv')
cit_16.to_csv('bloom_16.csv')
cit_bloom_merged = cit_bloom_merged.reset_index()
cit_bloom_merged

,index,Citation Number,Date Issued,Time Issued,Location,District,Cited Person Sex,Cited Person Race,Cited Person Age,Offense Code,Offense Description,Officer Age,Officer Sex,Officer Race,Quarter,Year
0,0,C10457,2019-02-16,16:05:00,S STATE ROAD 37 RAMP,LB523,M,W,48,9-18.1-11-2(b)(2),OPERATING WITH EXPIRED PLATES/IFC,26,M,W,1,2019
1,1,C10351,2019-02-03,09:46:00,121 E KIRKWOOD AVE,LB102,M,S,21,9-24-19-1,DRIVING WHILE SUSPENDED,26,M,W,1,2019
2,2,C10189,2019-01-15,14:27:00,W DODDS ST & S ROGERS ST,LB412,M,W,60,9-18.1-11-2(b)(2),OPERATING WITH EXPIRED PLATES/IFC,26,M,W,1,2019
3,3,C10685,2019-03-11,11:45:00,N MAPLE ST & W 11TH ST,LB518,F,B,20,9-21-8-32,DISREGARDING STOP SIGN,26,M,W,1,2019
4,4,C10085,2019-01-03,20:59:00,S WOODSCREST DR & E 2ND ST,LB304,F,W,41,9-19-6-3,NO OR IMPROPER HEADLIGHTS,26,M,W,1,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3869,1214,C6632,2017-10-18,23:35:00,W 11TH ST & N ROGERS ST,LB518,F,W,23,9-24-19-1,DRIVING WHILE SUSPENDED,24,M,B,4,2017
3870,1215,C7016,2017-12-04,01:54:00,S STATE ROAD 37 & W 3RD ST,LB524,F,W,55,9-21-3-7,DISREGARDING AUTOMATIC SIGNAL,41,F,W,4,2017
3871,1216,C6752,2017-10-30,08:08:00,W 3RD ST & S LIBERTY DR,LB403,M,W,48,9-18.1-2-3,REGISTRATION AND DISPLAY OF REGISTRATION,41,F,W,4,2017
3872,1217,C6752,2017-10-30,08:08:00,W 3RD ST & S LIBERTY DR,LB403,M,W,48,9-21-3-7,DISREGARDING AUTOMATIC SIGNAL,41,F,W,4,2017
3873,1218,C6602,2017-10-16,08:30:00,W 3RD ST & S JOHNSON AVE,LB404,F,W,24,9-21-5-2,SPEED MAXIMUM,41,F,W,4,2017

### Get the total number of persons by race per year

In [127]:
black_drive_stops_19 = sum([(cit_bloom_merged['Cited Person Race'] == 'B') & (cit_bloom_merged['Year'] == 2019)]).sum()   
white_drive_stops_19 = sum([(cit_bloom_merged['Cited Person Race'] == 'W') & (cit_bloom_merged['Year'] == 2019)]).sum()   
latinx_drive_stops_19 = sum([(cit_bloom_merged['Cited Person Race'] == 'L') & (cit_bloom_merged['Year'] == 2019)]).sum() + sum([(cit_bloom_merged['Cited Person Race'] == 'K') & (cit_bloom_merged['Year'] == 2019)]).sum() + sum([(cit_bloom_merged['Cited Person Race'] == 'N') & (cit_bloom_merged['Year'] == 2019)]).sum()  
asian_drive_stops_19 = sum([(cit_bloom_merged['Cited Person Race'] == 'A') & (cit_bloom_merged['Year'] == 2019)]).sum()     
other_drive_stops_19 = sum([(cit_bloom_merged['Cited Person Race'] == 'U') & (cit_bloom_merged['Year'] == 2019)]).sum() + sum([(cit_bloom_merged['Cited Person Race'] == 'I') & (cit_bloom_merged['Year'] == 2019)]).sum()

black_drive_stops_18 = sum([(cit_bloom_merged['Cited Person Race'] == 'B') & (cit_bloom_merged['Year'] == 2018)]).sum()   
white_drive_stops_18 = sum([(cit_bloom_merged['Cited Person Race'] == 'W') & (cit_bloom_merged['Year'] == 2018)]).sum()
latinx_drive_stops_18 = sum([(cit_bloom_merged['Cited Person Race'] == 'L') & (cit_bloom_merged['Year'] == 2018)]).sum() + sum([(cit_bloom_merged['Cited Person Race'] == 'K') & (cit_bloom_merged['Year'] == 2018)]).sum() + sum([(cit_bloom_merged['Cited Person Race'] == 'N') & (cit_bloom_merged['Year'] == 2018)]).sum()
asian_drive_stops_18 = sum([(cit_bloom_merged['Cited Person Race'] == 'A') & (cit_bloom_merged['Year'] == 2018)]).sum()     
other_drive_stops_18 = sum([(cit_bloom_merged['Cited Person Race'] == 'U') & (cit_bloom_merged['Year'] == 2018)]).sum() + sum([(cit_bloom_merged['Cited Person Race'] == 'I') & (cit_bloom_merged['Year'] == 2018)]).sum() + sum([(cit_bloom_merged['Cited Person Race'] == 'K') & (cit_bloom_merged['Year'] == 2018)]).sum()

black_drive_stops_17 = sum([(cit_bloom_merged['Cited Person Race'] == 'B') & (cit_bloom_merged['Year'] == 2017)]).sum() 
white_drive_stops_17 = sum([(cit_bloom_merged['Cited Person Race'] == 'W') & (cit_bloom_merged['Year'] == 2017)]).sum() 
latinx_drive_stops_17 = sum([(cit_bloom_merged['Cited Person Race'] == 'L') & (cit_bloom_merged['Year'] == 2017)]).sum() + sum([(cit_bloom_merged['Cited Person Race'] == 'K') & (cit_bloom_merged['Year'] == 2017)]).sum()  
asian_drive_stops_17 = sum([(cit_bloom_merged['Cited Person Race'] == 'A') & (cit_bloom_merged['Year'] == 2017)]).sum()    
other_drive_stops_17 = sum([(cit_bloom_merged['Cited Person Race'] == 'P') & (cit_bloom_merged['Year'] == 2017)]).sum()    
+ sum([(cit_bloom_merged['Cited Person Race'] == 'P') & (cit_bloom_merged['Year'] == 2017)]).sum()    
+ sum([(cit_bloom_merged['Cited Person Race'] == 'P') & (cit_bloom_merged['Year'] == 2017)]).sum()    

black_drive_stops_16 = sum(cit_16['Cited Person Race'] == 'B')
white_drive_stops_16 = sum(cit_16['Cited Person Race'] == 'W')
latinx_drive_stops_16 = sum(cit_16['Cited Person Race'] == 'L') + sum(cit_16['Cited Person Race'] == 'K')
asian_drive_stops_16 = sum(cit_16['Cited Person Race'] == 'A')
other_drive_stops_16 = sum(cit_16['Cited Person Race'] == 'U') +sum(cit_16['Cited Person Race'] == 'P')

## Population

### Population Data obtained from public city data

2016 population data was not available, so first filled them with 0 as a placeholder.

In [128]:
pop = pd.DataFrame(np.array([['Bloomington', '2019', 85755, .814, .043, .041, .099, .039],
                            ['Bloomington', '2018', 84981, .782, .0414, .0412, .0992, .03563],
                            ['Bloomington', '2017', 84896, .78, .041, .041, .099, .035],    # this is just an estimate, cannot find data for it
                            ['Bloomington', '2016', 84396, 0, 0, 0, 0, 0]
                            ]),
                   columns = ['City', 'Year', 'Total Population', 'White Percent', 'Black Percent', 
                              'Latinx Percent', 'Asian Percent', 'Other Percent (Including Multi-Racial)'])
pop

,City,Year,Total Population,White Percent,Black Percent,Latinx Percent,Asian Percent,Other Percent (Including Multi-Racial)
0,Bloomington,2019,85755,0.814,0.043,0.041,0.099,0.039
1,Bloomington,2018,84981,0.782,0.0414,0.0412,0.0992,0.03563
2,Bloomington,2017,84896,0.78,0.041,0.041,0.099,0.035
3,Bloomington,2016,84396,0,0,0,0,0

## Final Bloomington Dataframe

### Create a DataFrame including year, total population, population percent breakdowns, number of drive stops, and number of use of force incidences

Since 2016 data was not available, we thought it be best to just get the population data from the closest year to 2016, so we used the 2017 population data to represent an estimation of the 2016 population data.

In [129]:
final = pd.DataFrame(
    np.array(
        [
            [pop['City'][0], pop['Year'][0], pop['Total Population'][0], pop['Black Percent'][0], pop['White Percent']
             [0], pop['Latinx Percent'][0], pop['Asian Percent'][0], pop['Other Percent (Including Multi-Racial)'][0],
             black_drive_stops_19, white_drive_stops_19, latinx_drive_stops_19, asian_drive_stops_19, 
             other_drive_stops_19, black_uof_19, white_uof_19, latinx_uof_19, asian_uof_19, other_uof_19],
            [pop['City'][1], pop['Year'][1], pop['Total Population'][1], pop['Black Percent'][1], pop['White Percent']
             [1], pop['Latinx Percent'][1], pop['Asian Percent'][1], pop['Other Percent (Including Multi-Racial)'][1],
             black_drive_stops_18, white_drive_stops_18, latinx_drive_stops_18, asian_drive_stops_18, 
             other_drive_stops_18, black_uof_18, white_uof_18, latinx_uof_18, asian_uof_18, other_uof_18],
            [pop['City'][2], pop['Year'][2], pop['Total Population'][2], pop['Black Percent'][2], pop['White Percent']
             [2], pop['Latinx Percent'][2], pop['Asian Percent'][2], pop['Other Percent (Including Multi-Racial)'][2], 
             black_drive_stops_17, white_drive_stops_17, latinx_drive_stops_17, asian_drive_stops_17, 
             other_drive_stops_17, black_uof_17, white_uof_17, latinx_uof_17, asian_uof_17, other_uof_17],
            [pop['City'][3], pop['Year'][3], pop['Total Population'][3], pop['Black Percent'][2], pop['White Percent']
             [2], pop['Latinx Percent'][2], pop['Asian Percent'][2], pop['Other Percent (Including Multi-Racial)'][2],
             black_drive_stops_16, white_drive_stops_16, latinx_drive_stops_16, asian_drive_stops_16, 
             other_drive_stops_16, black_uof_16, white_uof_16, latinx_uof_16, asian_uof_16, other_uof_16]
        ]
    ),
    
    columns = ['city', 'year', 'total_pop', 'black_pct', 'white_pct', 'latinx_pct', 'asian_pct', 'other_pct', 
               'black_drive_stops', 'white_drive_stops', 'latinx_drive_stops', 'asian_drive_stops', 
               'other_drive_stops', 'black_uof', 'white_uof', 'latinx_uof', 'asian_uof', 'other_uof']
)
                               
final

,city,year,total_pop,black_pct,white_pct,latinx_pct,asian_pct,other_pct,black_drive_stops,white_drive_stops,latinx_drive_stops,asian_drive_stops,other_drive_stops,black_uof,white_uof,latinx_uof,asian_uof,other_uof
0,Bloomington,2019,85755,0.043,0.814,0.041,0.099,0.039,162,777,39,5,145,72.0,216.0,2.0,4.0,0.0
1,Bloomington,2018,84981,0.0414,0.782,0.0412,0.0992,0.03563,187,993,44,65,137,67.0,250.0,7.0,0.0,0.0
2,Bloomington,2017,84896,0.041,0.78,0.041,0.099,0.035,149,848,38,62,1,51.0,162.0,7.0,1.0,0.0
3,Bloomington,2016,84396,0.041,0.78,0.041,0.099,0.035,87,527,23,24,121,96.0,244.0,3.0,3.0,0.0

In [130]:
bloomington_csv = final.to_csv("bloomington.csv")

### Optional and has not been used, but this is the breakdown of percent of citer's vs. officer's race by population

In [131]:
percent_of_white_citers_16 = sum(cit_16['Cited Person Race'] == 'W') / (84396*0.78)
percent_of_black_citers_16 = sum(cit_16['Cited Person Race'] == 'B') / (84396*0.041)

percent_of_white_citers_17 = sum(cit_17['Cited Person Race'] == 'W') / (84396*0.78)
percent_of_black_citers_17 = sum(cit_17['Cited Person Race'] == 'B') / (84396*0.041)

percent_of_white_citers_18 = sum(cit_18['Cited Person Race'] == 'W') / (84981*0.782)
percent_of_black_citers_18 = sum(cit_18['Cited Person Race'] == 'B') / (84981*0.0414)

percent_of_white_citers_19 = sum(cit_19['Cited Person Race'] == 'W') / (85755*0.814)
percent_of_black_citers_19 = sum(cit_19['Cited Person Race'] == 'B') / (85755*0.043)

percent_of_white_officers_16 = sum(cit_16['Officer Race'] == 'W') / (84396*0.78)
percent_of_black_officers_16 = sum(cit_16['Officer Race'] == 'B') / (84396*0.041)

percent_of_white_officers_17 = sum(cit_17['Officer Race'] == 'W') / (84396*0.78)
percent_of_black_officers_17 = sum(cit_17['Officer Race'] == 'B') / (84396*0.041)

percent_of_white_officers_18 = sum(cit_18['Officer Race'] == 'W') / (84981*0.782)
percent_of_black_officers_18 = sum(cit_18['Officer Race'] == 'B') / (84981*0.0414)

percent_of_white_officers_19 = sum(cit_19['Officer Race'] == 'W') / (85755*0.814)
percent_of_black_officers_19 = sum(cit_19['Officer Race'] == 'B') / (85755*0.043)

white_citers = [percent_of_white_citers_16, percent_of_white_citers_17, percent_of_white_citers_18, percent_of_white_citers_19]
black_citers = [percent_of_black_citers_16, percent_of_black_citers_17, percent_of_black_citers_18, percent_of_black_citers_19]



white_officers = [percent_of_white_officers_16, percent_of_white_officers_17, percent_of_white_officers_18, percent_of_white_officers_19]
black_officers = [percent_of_black_officers_16, percent_of_black_officers_17, percent_of_black_officers_18, percent_of_black_officers_19]


bloom_percents = pd.DataFrame(columns = ['% of white citers', '% of black citers', '% of white officers', '% of black officers'])
bloom_percents['% of white citers'] = white_citers
bloom_percents['% of black citers'] = black_citers
bloom_percents['% of white officers'] = white_officers
bloom_percents['% of black officers'] = black_officers
bloom_percents['Year'] = [2016, 2017, 2018, 2019]
bloom_percents_csv = bloom_percents.to_csv('bloom_percents_race.csv')